---
name: build image

on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: blockloop/frp

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Get latest FRP release
        id: frp_version
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/fatedier/frp/releases/latest" | jq -r '.tag_name')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found FRP version: $VERSION"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.frp_version.outputs.version }},enable={{is_default_branch}}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: "${{ github.ref == 'refs/heads/master' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FRP_VERSION=${{ steps.frp_version.outputs.version }}
          cache-from: "type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache"
          cache-to: "type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max"
